export * from './divisao.js';
export * from './fatorial.js';
export * from './media.js';
export * from './multiplicacao.js';
export * from './porcentagem.js';
export * from './potencia.js';
export * from './raiz-quadrada.js';
export * from './soma.js';
export * from './subtracao.js';